# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Sets the version name and increments the version code"
  lane :release do |options|

    # set the version code and version name
    android_set_version_code(
      gradle_file: 'app/build.gradle.kts'
    )
    android_set_version_name(
      version_name: options[:version],
      gradle_file: 'app/build.gradle.kts'
    )
  end

  desc "Distribute builds via firebase"
  lane :firebase do
    app = "1:1037242127081:android:e6c38b03a4e11e46119678"
    credentials = "./app/google-services.json"

    # For firebase app distribution, we just use relative incremental numbers
    latest_release = firebase_app_distribution_get_latest_release(
      app: app,
      service_credentials_file: credentials
    )

    release = get_github_release(
      url: "AdGem/Android-Example",
      version: options[:version],
      api_token: ENV['GH_TOKEN']
    )

    gradle(
      task: ":app:clean :app:build"
    )

    firebase_app_distribution(
      app: app,
      credentials: credentials,
      groups: "qa-testers",
      release_notes: release["body"]
    )
  end

end