# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Sets the version name and increments the version code"
  lane :release do |options|

    # set the version code and version name
    android_set_version_code(
      gradle_file: 'build.gradle'
    )
    android_set_version_name(
      version_name: options[:version],
      gradle_file: 'build.gradle'
    )
  end

  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    upload_to_play_store
  end

end