name: fastlane-deploy-and-distribute

on:
  workflow_call:
  release:
    types: [published]

env:
  JAVA_VERSION: 17

jobs:
  fastlane-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Run Fastlane
        run: |
          bundle install
          bundle exec fastlane release version:$GITHUB_REF_NAME

  fastlane-distribute:
    needs: fastlane-release
    runs-on: ubuntu-latest
    steps:
      - name: Add Firebase Service Account to play store json credentials file
        run: |
          mkdir -p ./fastlane/gcp
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./fastlane/gcp/android-sdk-play-store.json
          ls -al
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Run Fastlane
        run: |
          ls -al
          bundle install
          bundle exec fastlane firebase
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}